import Head from "next/head";
import Footer from "components/Footer";
import Navbar from "components/Navbar";
import React from "react";

function MainLayout({ children }) {
  return (
    <>
      <Head>
        <title>Fylo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>
      <Navbar />
      <main>{children}</main>
      <Footer />
    </>
  );
}

export default MainLayout;
