import CTA from "components/CTA/CTA";
import Hero from "components/Hero/Hero";
import Productive from "components/Productive/Productive";
import MainLayout from "components/UI/MainLayout";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <Hero />
        <Productive />
        <CTA />
      </MainLayout>
    </div>
  );
}
